name: "Sub-Split Publishing"
on:
  push:
    branches:
      - "master"
  create:
    tags:
      - 'v*'
  delete:
    tags:
      - 'v*'

jobs:
  publish_subsplits:
    runs-on: ubuntu-latest
    name: "Publish package sub-splits"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
          persist-credentials: 'false'
      - uses: frankdejonge/use-github-token@1.0.1
        with:
          authentication: 'Slamdunk:${{ secrets.PERSONAL_ACCESS_TOKEN }}'
          user_name: 'Filippo Tessarotto'
          user_email: 'zoeslam@gmail.com'
      - name: "Cache splitsh-lite"
        id: splitsh-cache
        uses: actions/cache@v2
        with:
          path: './.splitsh'
          key: '${{ runner.os }}-splitsh'
      - uses: frankdejonge/use-subsplit-publish@1.0.0-beta.3
        with:
          source-branch: 'master'
          config-path: './config.subsplit-publish.json'
          splitsh-path: './.splitsh/splitsh-lite'
          splitsh-version: 'v1.0.1'
